language: php
php:
  - 5.3
  - 5.4

env:
  APPLICATION_ENV=automatedtests

script: phpunit --configuration phpunit.xml --coverage-text

before_script:
  - "php -m"
  - "wget http://getcomposer.org/composer.phar"
  - "php composer.phar install"
