language: php
php:
  - 5.3
  - 5.4

env:  

  global:
    - secure: 2c4b01333a324c2f104ffa9954f2d277e85bb8fd    
    - APPLICATION_ENV=automatedtests
    
script: phpunit --configuration=phpunit.xml --coverage-text

before_script:
  - mysql -e 'create database deputadosanalytics_test;'
  - "pear channel-discover pear.phpunit.de"
  - "pear install phpunit/DbUnit"  
  - "phpenv rehash"
  - "wget http://getcomposer.org/composer.phar"
  - "php composer.phar install"
  - "./tests/cli/console.php << EOF\nY EOF"
